name: Integracion Continua

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build-and-test:
    name: Compilar y ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v6

      - name: Configurar Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilar, ejecutar pruebas y generar reporte
        run: mvn --batch-mode clean test surefire-report:report-only

      - name: Publicar reporte HTML de pruebas
        uses: actions/upload-artifact@v7
        with:
          name: reporte-pruebas-junit
          path: target/reports/surefire.html
          if-no-files-found: error